name: generate arcade contribution graphs

on:
    schedule: # 매일 자정에 자동으로 실행
        - cron: '0 0 * * *'
    workflow_dispatch: # 수동으로 실행할 수 있게 설정
    push: # main 브랜치에 코드가 올라올 때마다 실행
        branches:
            - main

jobs:
    generate:
        permissions:
            contents: write
        runs-on: ubuntu-latest
        timeout-minutes: 20

        steps:
            - name: generate contribution graph SVGs
              uses: abozanona/pacman-contribution-graph@main
              with:
                  github_user_name: ${{ github.repository_owner }}
                  # puzzle-bobble을 추가했습니다. 다른 게임도 같이 보고 싶다면 쉼표(,)로 연결하면 됩니다.
                  games: 'puzzle-bobble'

            # 생성된 SVG 파일들을 output 브랜치에 저장합니다.
            - name: push SVGs to the output branch
              uses: crazy-max/ghaction-github-pages@v3.1.0
              with:
                  target_branch: output
                  build_dir: dist
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
